### ISSUE TITLE
I am unable to install spyder-vim by pip..PLZZZZ help

### ISSUE THREAD

**Issue by lihka1** [spyder-ide/spyder-vim#35] opened 2017-10-15 19:15 UTC
Thanks in advance

**Comment by andfoy** [comment] 2017-10-16 00:25
@lihka1 We haven't released Python packages yet. However, if you're installing from source, you can execute ``pip install .`` on the repo's root.

**Comment by andfoy** [comment] 2017-10-16 00:25
Closing as duplicate of #33

**Closed by andfoy** 2017-10-16 00:25 UTC

**Comment by lihka1** [comment] 2017-10-22 09:56
I installed from source and unable to see vim terminal....can you please help as i am a newbie..

**Comment by ayooshkathuria** [comment] 2018-02-23 04:47
@lihka1 
'git clone https://github.com/spyder-ide/spyder-vim`
`cd spyder-vim` 
`pip install .`

Restart spyder, you will find a text field besides the word "vim" at the bottom of the editor. Here you can execute vim commands.
