### ISSUE TITLE
conda installation

### ISSUE THREAD

**Issue by hendrikwout** [spyder-ide/spyder-vim#32] opened 2017-09-28 12:06 UTC
Hi,
I'm trying to install spyder-vim with latest conda installation version 4.3.25, but it doesn't seems to work.

Option 1: `conda install spyder-vim -c spyder-ide`
-> This says that the package is missing in the repository
Option 2: `pip install spyder-vim`
-> This seems to install, but then I see no option (or different behaviour) in Spyder.

Any ideas how to solve it?
Thanks!
Cheers,
Hendrik

**Comment by ccordoba12** [comment] 2017-09-28 15:37
This package has not been released yet. That's why there are no conda nor pip packages available, sorry.

**Comment by dcasasor** [comment] 2017-11-30 21:08
When are you planning to release the package? I'm sure lots of people like me are eager to use it!

**Comment by goanpeca** [comment] 2017-11-30 21:16
@dcasasor @hendrikwout we will try to make a release before the end of the year

**Comment by abracwan** [comment] 2020-08-15 10:31
Hi there. Although, a package is not available, is it possible to install this plugin from source on conda? I tried the following, but it didn't seem to work:

1. Cloned `spyder-vim` repository
2. Copied `spyder_vim` folder to `anaconda3/pkgs/spyder-4.0.1-py37_0/lib/python3.7/site-packages/spyder/plugins/`
3. Restarted Spyder.

Not sure if this process is correct for Conda users? Hope someone can advise.

**Comment by kcmeehan** [comment] 2021-02-09 21:27
Hi all. I installed Spyder on Windows with the standalone installer. I then cloned and pip installed spyder-vim in the virtual environment whose python my Spyder points to. If I open Spyder directly then I do not see the vim command line bar. If I open Spyder from within the gitbash terminal, I can see the vim commandline that seems to work but then Spyder segfaults within 30 secs every time. Is there a workaround for this?

**Comment by ccordoba12** [comment] 2021-02-10 17:08
@kcmeehan, our installers are completely self-contained, so our third-party plugins can't be installed in them. We plan to fix that limitation later this year.

**Comment by dcstang** [comment] 2022-03-25 11:11
Hope the conda package can be released eventually! My org only allows conda packages internally. Thanks for the good work.

**Comment by dalthviz** [comment] 2022-09-26 17:25
Closing as duplicate of #22 

To follow up the progress towards the initial release for this plugin/package you can check #78

**Closed by dalthviz** 2022-09-26 17:25 UTC
Labels: type:Task, reso:duplicate
